name: deep_dreaming
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=2.0.1
  - future=0.18.3
  - importlib-metadata=7.2.0
  - importlib_metadata=7.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.29.4
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - libsodium=1.0.18
  - libuv=1.44.2
  - matplotlib-inline=0.1.7
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nest-asyncio=1.6.0
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.24.3
  - openssl=3.0.14
  - packaging=24.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.18.0
  - python=3.9.16
  - python_abi=3.9
  - pytorch=1.12.1
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tornado=6.2
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wcwidth=0.2.13
  - wheel=0.43.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - pip:
      - ase==3.23.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.0
      - global-chem==1.9.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - matplotlib==3.6.2
      - networkx==3.2.1
      - numpy==1.23.5
      - pandas==2.2.2
      - pbr==6.0.0
      - pillow==10.3.0
      - pyparsing==3.1.2
      - pysmiles==1.1.2
      - pormake==0.2.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - rdkit==2022.9.4
      - scikit-learn==1.5.0
      - scipy==1.10.1
      - selfies==2.1.1
      - threadpoolctl==3.5.0
      - tqdm==4.66.4
      - tzdata==2024.1
